In [2]:
import numpy as np

# Numpy配列の作り方

## 配列の生成

In [9]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])

## 次元数・要素数・何行何列・要素の型

In [11]:
a.ndim, a.size, a.shape, a.dtype

(2, 10, (2, 5), dtype('int64'))

## ゼロ行列・イチ行列

In [12]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
zeros, ones

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

## 規則的な配列の生成
- np.arange(始, 終, 間隔)
- arangeは終わりの値を**含まない**

- np.linspace(始, 終, 個数)
- linspaceは終わりの値を**含む**

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [3]:
np.linspace(0, np.pi, 10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

## 配列の整形
- reshape(h, w)：h行w列の行列に変換
- .T, transpose()：行列の転置を行う
- ravel()：１次元の行列にする
- どれも元の配列には影響しないメソッド

In [8]:
array = np.arange(1, 7)
print(array)
array = array.reshape(2, 3)
print(array)
array = array.T
print(array)
array = array.ravel()
print(array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [10]:
# 演習１
a = np.arange(15)
print(a)
b = a.reshape(3, 5)
print(b)
print(a.shape, b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(15,) (3, 5)


# Numpy配列に対する数学的演算

## 四則演算
- 基本的には普通の演算子を使うだけ

In [11]:
a = np.array([0, 1, 2, 3])
b = np.array([3, 2, 1, 0])
print(a+b)
print(a-b)
print(a*b)

[3 3 3 3]
[-3 -1  1  3]
[0 2 2 0]


## 行列積は二種類ある
- 同じ要素番号同士の掛け算は *
- 行列の掛け算は A.dot(B) or np.dot(A, B)

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A*B)
print(np.dot(A, B))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


## 統計的な演算
### 総和・最小値・最大値・平均値・標準偏差

In [14]:
a = np.array([1, 2, 3, 4, 5])
print(a.sum(), a.min(), a.max(), a.mean(), a.std())

15 1 5 3.0 1.4142135623730951


## Numpy配列における軸の概念
- 行ごとの和、列ごとの和を求めるときは**axis**を使う 

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 列ごとの和
print(a.sum(axis=0))
# 行ごとの和
print(a.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [17]:
# 演習２
a = np.arange(1, 11)
print(a)
a = a.reshape(2, 5)
print(a)
b0 = np.arange(1, 6)
b1 = np.arange(6, 11)
print(b0 + b1)
print(b0 - b1)
print(b0 * b1)
print(b0 / b1)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# 配列のデータ参照

## 1次元配列における参照

In [19]:
a = np.array(["あ", "い", "う", "え", "お"])
print(a[2])
print(a[-2])
#0番目と2番目を取り出したいときは、リストで指定する
print(a[[0, 2]])
#スライスを使うこともできる
print(a[1:3])
print(a[0:4:2])

う
え
['あ' 'う']
['い' 'う']
['あ' 'う']


## 2次元配列における参照

In [20]:
b = np.array([[1, 2, 3], [4, 5, 6]])
# 1行2列目の取り出し
print(b[1, 2])
# 2列目の取り出し
print(b[:, 2])

6
[3 6]


## 条件にあった要素の抜き出し
- np.where(条件, 真の場合の処理, 偽の場合の処理)

In [28]:
a = np.arange(20).reshape(4, 5)
print(np.where(a % 3 == 0, 1, 0))

[[1 0 0 1 0]
 [0 1 0 0 1]
 [0 0 1 0 0]
 [1 0 0 1 0]]


In [31]:
# 演習3

array = np.arange(1, 26).reshape(5, 5)
print(array)
print(array[1:3, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8]
 [12 13]]
