In [7]:
import numpy as np

## 配列の生成

In [9]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])

## 次元数・要素数・何行何列・要素の型

In [11]:
a.ndim, a.size, a.shape, a.dtype

(2, 10, (2, 5), dtype('int64'))

## ゼロ行列・イチ行列

In [12]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
zeros, ones

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

## 規則的な配列の生成
- np.arange(始, 終, 間隔)
- arangeは終わりの値を**含まない**

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])